name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLProject/dataset/failure_heart_preprocessing.csv"
  TARGET_VAR: "HeartDisease"
  EXPERIMENT_NAME: "CI/CD Heart Disease Model"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      MLFLOW_TRACKING_URI: "https://dagshub.com/fahrimuda12/heart-disease.mlflow"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.9
          activate-environment: heart_disease_env
      
      - name: Install MLflow
        shell: bash -l {0}
        run: |
          conda activate heart_disease_env
          pip install mlflow
      
      - name: Verify installation
        shell: bash -l {0}
        run: |
          conda activate heart_disease_env
          mlflow --version
          python --version
      
      - name: Export env
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/fahrimuda12/heart-disease.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_TOKEN=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV
          echo "DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV
          echo "DAGSHUB_USERNAME=${{ secrets.DAGSHUB_USERNAME }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=${{ secrets.DAGSHUB_USERNAME }}" >> $GITHUB_ENV

      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          conda activate heart_disease_env
          cd MLProject 
          mlflow run . --experiment-name "model_heart_disease_failure"
      
      - name: List generated artifacts
        shell: bash -l {0}
        run: |
          echo "Generated files:"
          find MLProject/ -name "*.pkl" -o -name "*.joblib" -o -name "mlruns" | head -20
      
      - name: Show MLflow runs
        shell: bash -l {0}
        run: |
          cd MLProject
          echo "MLflow runs:"
          ls -la mlruns/ 2>/dev/null || echo "No mlruns directory found"

      # # Save models to GitHub Repository
      # - name: Save mlruns to repo
      #   run: |
      #     git config --global user.name ${{ secrets.username }}
      #     git config --global user.email ${{ secrets.email }}
      #     git add MLProject/model_heart_disease_failure/
      #     git commit -m "Save mlruns from CI run"
      #     git push origin master

      # Get latest run_id
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td MLProject/model_heart_disease_failure/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"
          
      # Build Docker Model
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "heart_disease" 

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Tag the Docker image
      - name: Tag Docker Image
        run: |
          docker tag heart_disease ${{ secrets.DOCKER_HUB_USERNAME }}/heart_disease:latest

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/heart_disease:latest